#Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
  default_locale: en

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    bind:
      $listBuilderFactory: '@sulu_core.doctrine_list_builder_factory'
      $mediaRepository: '@sulu.repository.media'
      $mediaManager: '@sulu_media.media_manager'

  _instanceof:
    Sulu\Bundle\AdminBundle\Admin\Admin:
      tags: ['sulu.admin', {name: 'sulu.context', context: 'admin'}]

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']


  App\Bundle\ArticleBundle\Content\ArticleSelectionContentType:
    tags: [{name: 'sulu.content.type', alias: 'article_selection'}]

  App\Bundle\ArticleBundle\Content\ArticleDataProvider:
    tags: [{name: 'sulu.smart_content.data_provider', alias: 'articles'}]
    bind:
      $repository: '@App\Bundle\ArticleBundle\Repository\ArticleRepository'

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  # following service definitions will be removed in the website context of sulu
  App\Bundle\ArticleBundle\Admin\:
    resource: '../src/Bundle/ArticleBundle/Admin'
    tags: [{name: 'sulu.context', context: 'admin'}]

  App\Bundle\ArticleBundle\Controller\Admin\:
    resource: '../src/Bundle/ArticleBundle/Controller/Admin'
    tags: [{name: 'sulu.context', context: 'admin'}]

  App\Bundle\ArticleBundle\Repository\:
    resource: '../src/Bundle/ArticleBundle/Repository'
    public: true